### ISSUE TITLE
似乎和loadout 改卡机和奇美拉卡牌有冲突

### ISSUE THREAD

**Issue by pphelper** [purcolin/SlayTheAberration#1]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.StackOverflowError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.StackOverflowError
	at com.megacrit.cardcrawl.cards.AbstractCard.initializeDescriptionCN(AbstractCard.java)
	at com.megacrit.cardcrawl.cards.AbstractCard.initializeDescription(AbstractCard.java:471)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:398)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:294)
	at com.megacrit.cardcrawl.cards.red.FlameBarrier.<init>(FlameBarrier.java:20)
	at com.megacrit.cardcrawl.cards.red.FlameBarrier.makeCopy(FlameBarrier.java:59)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:978)
	at CardAugments.cardmods.rare.AlphaMod.onInitialApplication(AlphaMod.java:29)
	at basemod.helpers.CardModifierManager.lambda$copyModifiers$6(CardModifierManager.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at basemod.helpers.CardModifierManager.copyModifiers(CardModifierManager.java:140)
	at aberration.patch.CardCopyWithModPatch.Insert(CardCopyWithModPatch.java:21)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:984)
	at CardAugments.cardmods.rare.AlphaMod.onInitialApplication(AlphaMod.java:29)
	at basemod.helpers.CardModifierManager.lambda$copyModifiers$6(CardModifierManager.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at basemod.helpers.CardModifierManager.copyModifiers(CardModifierManager.java:140)
	at aberration.patch.CardCopyWithModPatch.Insert(CardCopyWithModPatch.java:21)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:984)
	at CardAugments.cardmods.rare.AlphaMod.onInitialApplication(AlphaMod.java:29)
	at basemod.helpers.CardModifierManager.lambda$copyModifiers$6(CardModifierManager.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at basemod.helpers.CardModifierManager.copyModifiers(CardModifierManager.java:140)
	at aberration.patch.CardCopyWithModPatch.Insert(CardCopyWithModPatch.java:21)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:984)
	at CardAugments.cardmods.rare.AlphaMod.onInitialApplication(AlphaMod.java:29)
	at basemod.helpers.CardModifierManager.lambda$copyModifiers$6(CardModifierManager.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at basemod.helpers.CardModifierManager.copyModifiers(CardModifierManager.java:140)
	at aberration.patch.CardCopyWithModPatch.Insert(CardCopyWithModPatch.java:21)
	at com.megacrit.cardcrawl.cards.AbstractCard.makeStatEquivalentCopy(AbstractCard.java:984)
	at CardAugments.cardmods.rare.AlphaMod.onInitialApplication(AlphaMod.java:29)
	at basemod.helpers.CardModifierManager.lambda$copyModifiers$6(CardModifierManager.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1249)

**Comment by purcolin** [comment]
这是貌似出现了死循环，我还没有检查过与奇美拉的兼容性，我会尽快修复它

**Comment by purcolin** [comment]
最后大概是由于一段已废弃（或者是我忘记了其作用）的代码导致的错误，举个例子奇美拉创建“阿尔法打击”修改时会生成“贝塔打击”与“欧米茄打击”的预览，但是由于那段代码，在生成预览时会生成“阿尔法贝塔打击”，这时候又会生成“阿尔法贝塔贝塔打击”的预览，由此产生了循环......不过好在我的卡牌修改与奇美拉的用的相同的api，所以兼容性算是比较好搞定的
