### ISSUE TITLE
第四关精英崩溃

### ISSUE THREAD

**Issue by pphelper** [purcolin/SlayTheAberration#2]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_144]
	at aberration.AberrationMod.receiveOnBattleStart(AberrationMod.java:170) ~[aberration.jar:?]
	at basemod.BaseMod.publishStartBattle(BaseMod.java:2597) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.rooms.AbstractRoom.StartBattleHook.Insert(StartBattleHook.java:20) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:295) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
第四关进精英房就崩溃了，不确定是默认的矛和盾，有MOD可以把它们替换成别的怪物
虫群畸变的幼虫出生位置能限制在一定范围内吗，好像有几率出现在屏幕外面点不到

**Comment by purcolin** [comment]
收到，四层我还没有写，我可以修一下让第四层不做修改。虫群可能是分辨率不同的问题，我会尝试在不同分辨率测试的
